# Generated by Django 2.2.2 on 2019-10-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlignmentDateTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_id', models.CharField(db_index=True, max_length=255)),
                ('date_modified', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Date example',
                'verbose_name_plural': 'Date examples',
            },
        ),
        migrations.CreateModel(
            name='AlignmentStringTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_id', models.CharField(db_index=True, max_length=255)),
                ('date_modified', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'String example',
                'verbose_name_plural': 'String examples',
            },
        ),
        migrations.CreateModel(
            name='AlignmentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_id', models.CharField(db_index=True, max_length=255)),
                ('date_modified', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'No partition',
                'verbose_name_plural': 'No partition',
            },
        ),
    ]
